companies:
  - name: google
    keywords: 
      - software engineer intern
      - ai
      - data science inter
      - data scientist
      - researcher
      - engineer
      - software
      - program
      - early
      - intern
      - internship
      - fellow
      - intern 2025
      - data
      - scientist