companies:
  - name: google
    keywords: 
      - software engineer intern
      - ai
      - ai intern
      - ai engineer
      - machine learning
      - computer vision
      - gen ai
      - machine learning intern
      - generative ai intern
      - generative ai intern
      - generative ai
      - data science intern
      - data scientist
      - researcher
      - engineer
      - software
      - program
      - early
      - intern
      - internship
      - fellow
      - intern 2025
      - data
      - scientist